### ISSUE TITLE
numpy 1.13.1 vs 1.12.1

### ISSUE THREAD

**Issue by tdiethe** [IRC-SPHERE/HyperStreamOnlineLearning#6]
Currently specified is `numpy 1.13.1`. I have `numpy 1.12.1` as I'm using `python-spams` which takes that exact version as a dependency - is there a hard requirement for 1.13.1? This is the problem with dependencies! Can fix with a virtual environment I realise but might save others some pain to change this.

**Comment by perellonieto** [comment]
I don't think it is a hard dependency. I just added my current version as a requirement.
I will try the code with that version and let you know the result.
